include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
  plugins:
    - custom_lint
linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: true
    require_trailing_commas: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
