import '../models/file_card.dart';

List<FileCardData> sampleFiles = [
  FileCardData(
    fileName: 'team_photo_retouched.png',
    size: '2.7 MB',
    description: 'Official team photo, 4k resolution',
    typeLabel: 'Image',
    isPreviewable: true,
    uploadedBy: 'David Chen',
    uploadDate: DateTime(2025, 6, 11, 14, 32),
  ),
  FileCardData(
    fileName: 'marketing_brief_2025_v3.docx',
    size: '134 kB',
    description: 'Final marketing brief with edits',
    typeLabel: 'Doc',
    isPreviewable: false, // assume you don’t preview .docx inline
    uploadedBy: 'Sofia López',
    uploadDate: DateTime(2025, 5, 29, 9, 8),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
  FileCardData(
    fileName: 'financial_report_Q2_2024.pdf',
    size: '842 kB',
    description: 'Board-ready finance report',
    typeLabel: 'PDF',
    isPreviewable: true,
    uploadedBy: 'Emma Rossi',
    uploadDate: DateTime(2024, 8, 2, 17, 55),
  ),
];
